// Code generated by genum DO NOT EDIT

package countries

// type definition
type Country struct {
	name      string
	shorthand string
	continent string
}

// countries
var (
	TR = Country{
		name: "Turkey",
	}

	NL = Country{
		name: "The Netherlands",
	}

	JP = Country{
		name: "Japan",
	}
)

func (c Country) Name() string {
	return c.name
}

func (c Country) Shorthand() string {
	return c.shorthand
}

func (c Country) Continent() string {
	return c.continent
}

func AllCountries() []Country {
	return []Country{TR, NL, JP}
}
