// Code generated by genum DO NOT EDIT

package countries

// type definition
type (
	Country struct {
		name string
	}
)

// countries
var (
	TR = Country{
		name: "a",
	}
	CD = Country{
		name: "a",
	}
)

func (c Country) Name() string {
	return c.name
}
func AllCountries() []Country {
	return []Country{
		TR,
	}
}
